<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <ClInclude Include="$(MSBuildThisFileDirectory)GlassSurfaceGpu.h" />
    <ClInclude Include="$(MSBuildThisFileDirectory)GlassRegionGpu.h" />
    <ClInclude Include="$(MSBuildThisFileDirectory)GlassFgPass.h" />
    <ClInclude Include="$(MSBuildThisFileDirectory)CyberpunkSurfacePass.h" />
    <ClInclude Include="$(MSBuildThisFileDirectory)SurfaceQueueLink.h" />
    <ClCompile Include="$(MSBuildThisFileDirectory)GlassFgCompile.cpp" />
    <None Include="$(MSBuildThisFileDirectory)GlassSurface.hlsl" />
    <None Include="$(MSBuildThisFileDirectory)GlassRegion.hlsl" />
  </ItemGroup>
</Project>
